services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    ports:
      - "5000:8080"

  spieler:
    image: ${DOCKER_REGISTRY-}spieler
    build:
      context: .
      dockerfile: src/Spieler/Dockerfile

  kickern:
    image: ${DOCKER_REGISTRY-}kickern
    build:
      context: .
      dockerfile: src/Kickern/Dockerfile
